// Decodes the activation token the customer pastes into checkout. The token
// is generated by their Infrawatch install and carries the install's
// organisation id, which we stamp into the licence JWT's `sub` claim so the
// resulting licence can only be activated on that install.
//
// This file is kept in sync with apps/web/lib/licence-activation-token.ts —
// same prefix, same version, same schema.

const TOKEN_PREFIX = 'infw-act_'
const TOKEN_VERSION = 1
const MAX_TOKEN_AGE_DAYS = 30

export type ActivationTokenPayload = {
  v: number
  installOrgId: string
  installOrgName: string
  generatedAt: string
  nonce: string
}

export type ActivationTokenDecodeResult =
  | { ok: true; payload: ActivationTokenPayload }
  | { ok: false; error: string }

function fromBase64Url(input: string): string {
  const padded = input.replace(/-/g, '+').replace(/_/g, '/')
  const pad = padded.length % 4 === 0 ? '' : '='.repeat(4 - (padded.length % 4))
  return Buffer.from(padded + pad, 'base64').toString('utf8')
}

export function decodeActivationToken(raw: string): ActivationTokenDecodeResult {
  const trimmed = raw.trim()
  if (!trimmed.startsWith(TOKEN_PREFIX)) {
    return { ok: false, error: 'Token is not a valid activation token' }
  }
  const body = trimmed.slice(TOKEN_PREFIX.length)
  if (!body) {
    return { ok: false, error: 'Activation token is empty' }
  }

  let parsed: unknown
  try {
    parsed = JSON.parse(fromBase64Url(body))
  } catch {
    return { ok: false, error: 'Activation token is malformed' }
  }

  if (!parsed || typeof parsed !== 'object') {
    return { ok: false, error: 'Activation token is malformed' }
  }
  const p = parsed as Record<string, unknown>

  if (p.v !== TOKEN_VERSION) {
    return { ok: false, error: `Unsupported activation token version: ${String(p.v)}` }
  }
  if (typeof p.installOrgId !== 'string' || !p.installOrgId) {
    return { ok: false, error: 'Activation token is missing installOrgId' }
  }
  if (typeof p.installOrgName !== 'string' || !p.installOrgName) {
    return { ok: false, error: 'Activation token is missing installOrgName' }
  }
  if (typeof p.generatedAt !== 'string' || !p.generatedAt) {
    return { ok: false, error: 'Activation token is missing generatedAt' }
  }
  if (typeof p.nonce !== 'string' || !p.nonce) {
    return { ok: false, error: 'Activation token is missing nonce' }
  }

  const generatedAt = new Date(p.generatedAt)
  if (Number.isNaN(generatedAt.getTime())) {
    return { ok: false, error: 'Activation token has an invalid timestamp' }
  }
  const ageDays = (Date.now() - generatedAt.getTime()) / (24 * 60 * 60 * 1000)
  if (ageDays > MAX_TOKEN_AGE_DAYS) {
    return { ok: false, error: 'Activation token has expired — generate a new one' }
  }
  if (generatedAt.getTime() > Date.now() + 5 * 60 * 1000) {
    return { ok: false, error: 'Activation token is dated in the future' }
  }

  return {
    ok: true,
    payload: {
      v: TOKEN_VERSION,
      installOrgId: p.installOrgId,
      installOrgName: p.installOrgName,
      generatedAt: p.generatedAt,
      nonce: p.nonce,
    },
  }
}
